#!/bin/bash
# eXtreme Feedback Device
# USB connected device which switches some LEDs on and off
# script to test basic functionality
#
# Copyright (C) 2012 Holger Oehm
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usbleds r
sleep 10
usbleds ry
sleep 2
usbleds g
sleep 10
usbleds y
sleep 2
usbleds r
sleep 10
usbleds o
